name: maroid

services:
  postgres:
    image: "timescale/timescaledb:2.25.1-pg17-oss"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-maroid}
      POSTGRES_USER: ${POSTGRES_USER:-maroid}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-maroid}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  emqx:
    image: "emqx/emqx:5.10.3"
    volumes:
      - "emqx_data:/opt/emqx/data"
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:18083:18083"
    healthcheck:
      test: [ "CMD", "emqx", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ngrok:
    image: "ngrok/ngrok:3.25.0-alpine"
    command:
      - "http"
      - "http://host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "127.0.0.1:4040:4040"

volumes:
  postgres_data:
  emqx_data:
